services:
  weight-sync:
    image: ghcr.io/watsona4/weight-sync:latest
    build: .
    restart: unless-stopped
    volumes:
      - ./data:/data
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
    networks:
      - weight-sync
    environment:
      REDIS_HOST: cache
      REDIS_PORT: 6379
    env_file:
      - .env
    depends_on:
      - nginx
      - redis
    healthcheck:
      test: curl -f http://localhost:8000/health
  nginx:
    image: nginx:latest
    restart: always
    volumes:
      - ./nginx/templates:/etc/nginx/templates:ro
    ports:
      - 8568:8080
    networks:
      - weight-sync
    healthcheck:
      test: curl -f http://localhost:8080/health
  poller:
    image: ghcr.io/watsona4/weight-sync-poller:latest
    build: poller
    restart: unless-stopped
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
    env_file:
      - .env
    depends_on:
      - nginx
      - weight-sync
  redis:
    image: redis:6.2-alpine
    restart: always
    ports:
      - 6379:6379
    command: redis-server --save 60 1 --requirepass ${REDIS_PASSWORD}
    volumes: 
      - redis:/data
    env_file:
      - .env
    networks:
      - weight-sync
    healthcheck:
      test: redis-cli -a ${REDIS_PASSWORD} --raw incr ping

networks:
  weight-sync:
    driver: bridge

volumes:
  redis:
    driver: local